baseurl: /blog
production_url: http://cfxyz.com/blog
highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM
  auto_ids:      true
  auto_id_prefix: 'id-'
  extensions:
    - autolink
    - footnotes
    - smart
  enable_coderay: true
  syntax_highlighter: rouge
  
gems: [jekyll-paginate]

paginate: 10
paginate_path: "/page:num" 
