baseurl: /blog
production_url: http://cfxyz.com/blog
markdown: redcarpet
redcarpet:
  extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]

paginate: 10
paginate_path: "/page:num" 
